"use client"

import { useMemo, useState, useTransition } from "react"
import { useI18n } from "@/components/language-provider"
import { activityTypeKey, typeStyles } from "@/lib/activity-format"
import { deleteEntry } from "@/app/actions/time-entries"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ChevronLeft, ChevronRight, Download, Trash2 } from "lucide-react"

type Entry = { id:number; date:string; type:string; title:string; hours:string; status:string; notes:string|null }
export function TimesheetView({ initialEntries, year: initialYear, month: initialMonth }: { initialEntries: Entry[]; year:number; month:number }) {
 const {t,lang}=useI18n(); const [cursor,setCursor]=useState(new Date(initialYear,initialMonth,1)); const [entries,setEntries]=useState(initialEntries); const [pending,setPending]=useState<number|null>(null); const locale=lang==="sk"?"sk-SK":"en-GB"
 const monthName=cursor.toLocaleDateString(locale,{month:"long",year:"numeric"}); const total=useMemo(()=>entries.reduce((s,e)=>s+Number(e.hours),0),[entries])
 const move=async(d:number)=>{const next=new Date(cursor.getFullYear(),cursor.getMonth()+d,1); setCursor(next); const res=await fetch(`/api/timesheet?year=${next.getFullYear()}&month=${next.getMonth()}`); if(res.ok)setEntries(await res.json())}
 const remove=async(id:number)=>{setPending(id); await deleteEntry(id); setEntries(e=>e.filter(x=>x.id!==id)); setPending(null)}
 const exportCsv=()=>{const head=[t.date,t.activity,t.type,t.hours,t.status]; const rows=entries.map(e=>[e.date,e.title,t[activityTypeKey[e.type]??"type_other"],e.hours,e.status].map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')); const blob=new Blob([[head.join(','),...rows].join('\n')],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`worktime-${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}.csv`; a.click(); URL.revokeObjectURL(url)}
 return <div className="flex flex-col gap-6"><header><h1 className="font-serif text-3xl font-semibold">{t.monthlyRecord}</h1><p className="mt-1 text-sm text-muted-foreground">{t.timesheetSubtitle}</p></header><div className="flex flex-wrap items-center gap-2"><Button variant="outline" size="icon" onClick={()=>move(-1)}><ChevronLeft/></Button><div className="min-w-48 text-center font-serif text-lg font-semibold capitalize">{monthName}</div><Button variant="outline" size="icon" onClick={()=>move(1)}><ChevronRight/></Button><Button variant="outline" className="ml-auto" onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>{t.export}</Button></div><Card className="p-5"><p className="text-sm text-muted-foreground">{t.totalHours}</p><p className="mt-1 font-serif text-4xl font-semibold">{total.toFixed(2)} h</p></Card><Card className="overflow-x-auto p-0"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground">{[t.date,t.activity,t.type,t.hours,t.status,t.actions].map(x=><th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{entries.length===0?<tr><td colSpan={6} className="p-10 text-center text-muted-foreground">{t.noRecords}</td></tr>:entries.map(e=>{const s=typeStyles[e.type]??typeStyles.other;return <tr key={e.id} className="border-b last:border-0"><td className="whitespace-nowrap px-4 py-3">{e.date}</td><td className="px-4 py-3 font-medium">{e.title}</td><td className="px-4 py-3"><span className={`rounded-full border px-2 py-0.5 text-[11px] ${s.badge}`}>{t[activityTypeKey[e.type]??"type_other"]}</span></td><td className="px-4 py-3 font-mono">{Number(e.hours).toFixed(2)} h</td><td className="px-4 py-3">{t[`status_${e.status}` as keyof typeof t] ?? e.status}</td><td className="px-4 py-3"><Button variant="ghost" size="icon" disabled={pending===e.id} onClick={()=>remove(e.id)} aria-label={t.delete}><Trash2 className="h-4 w-4"/></Button></td></tr>})}</tbody></table></Card></div>
}
