"use client"

import { useMemo, useState } from "react"
import { useI18n } from "@/components/language-provider"
import { activityTypeKey, typeStyles } from "@/lib/activity-format"
import { deleteEntry } from "@/app/actions/time-entries"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ChevronLeft, ChevronRight, Download, Trash2 } from "lucide-react"

type Entry={id:number;date:string;type:string;title:string;hours:string;status:string;notes:string|null}
export function TimesheetView({initialEntries,year:initialYear,month:initialMonth}:{initialEntries:Entry[];year:number;month:number}){
 const {t,lang}=useI18n();const [cursor,setCursor]=useState(new Date(initialYear,initialMonth,1));const [entries,setEntries]=useState(initialEntries);const locale=lang==="sk"?"sk-SK":"en-GB";const monthName=cursor.toLocaleDateString(locale,{month:"long",year:"numeric"});const total=useMemo(()=>entries.reduce((s,e)=>s+Number(e.hours),0),[entries]);const rehearsals=entries.filter(e=>e.type==="rehearsal").length;const concerts=entries.filter(e=>e.type==="concert").length
 const move=async(d:number)=>{const next=new Date(cursor.getFullYear(),cursor.getMonth()+d,1);setCursor(next);const res=await fetch(`/api/timesheet?year=${next.getFullYear()}&month=${next.getMonth()}`);if(res.ok)setEntries(await res.json())};const remove=async(id:number)=>{await deleteEntry(id);setEntries(x=>x.filter(e=>e.id!==id))};const exportCsv=()=>{const head=[t.date,t.activity,t.type,t.hours,t.status];const rows=entries.map(e=>[e.date,e.title,t[activityTypeKey[e.type]??"type_other"],e.hours,e.status].map(x=>`"${String(x).replaceAll('"','""')}"`).join(','));const blob=new Blob([[head.join(','),...rows].join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`worktime-${cursor.getFullYear()}-${cursor.getMonth()+1}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="flex flex-col gap-5 pb-3"><header><h1 className="font-serif text-[28px] font-semibold">{t.monthlyRecord}</h1></header><div className="flex items-center justify-between"><Button variant="outline" size="icon" className="rounded-xl" onClick={()=>move(-1)}><ChevronLeft/></Button><p className="font-semibold capitalize">{monthName}</p><Button variant="outline" size="icon" className="rounded-xl" onClick={()=>move(1)}><ChevronRight/></Button></div><div className="grid grid-cols-3 gap-2.5"><Card className="rounded-xl border-0 bg-[#edf8f2] p-3 text-center shadow-none"><p className="font-serif text-[22px] font-semibold text-emerald-800">{total.toFixed(1)}</p><p className="text-[10px] text-emerald-700">{t.totalHours}</p></Card><Card className="rounded-xl border-0 bg-[#eef4ff] p-3 text-center shadow-none"><p className="font-serif text-[22px] font-semibold text-blue-800">{rehearsals}</p><p className="text-[10px] text-blue-700">{t.type_rehearsal}</p></Card><Card className="rounded-xl border-0 bg-[#fff0f2] p-3 text-center shadow-none"><p className="font-serif text-[22px] font-semibold text-rose-700">{concerts}</p><p className="text-[10px] text-rose-700">{t.type_concert}</p></Card></div><section className="space-y-3">{entries.length===0?<Card className="rounded-xl p-8 text-center text-sm text-muted-foreground">{t.noRecords}</Card>:entries.map(e=>{const s=typeStyles[e.type]??typeStyles.other;return <Card key={e.id} className="rounded-xl p-4 shadow-none"><div className="flex items-center gap-3"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${s.dot}`}/><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{e.title}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{e.date}</p><span className={`mt-1 inline-block rounded-full border px-2 py-0.5 text-[10px] ${s.badge}`}>{t[activityTypeKey[e.type]??"type_other"]}</span></div><span className="font-mono text-sm font-semibold">{Number(e.hours).toFixed(1)} h</span><Button variant="ghost" size="icon" onClick={()=>remove(e.id)}><Trash2 className="h-4 w-4"/></Button></div></Card>})}</section><Button variant="outline" className="w-full rounded-xl" onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>{t.export}</Button></div>
}
