"use client"

import { useMemo, useState, useTransition } from "react"
import { useI18n } from "@/components/language-provider"
import { addVideo } from "@/app/actions/videos"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Play, Plus, Loader2, Music2, Search, ExternalLink, LibraryBig } from "lucide-react"

type Video={id:number;title:string;date:string|null;conductor:string|null;venue:string|null;description:string|null;url:string|null;thumbnailUrl:string|null}

export function VideosView({initialVideos,seedVideos,syncArchive}:{initialVideos:Video[];seedVideos:()=>Promise<{seeded:boolean}>;syncArchive:()=>Promise<{synced:boolean;count:number}>}){
 const {t}=useI18n(); const [videos,setVideos]=useState(initialVideos); const [open,setOpen]=useState(false); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [pending,startTransition]=useTransition()
 const [form,setForm]=useState({title:"",date:"",conductor:"",venue:"",description:"",url:""}); const set=(k:keyof typeof form,v:string)=>setForm(x=>({...x,[k]:v}))
 const seed=()=>startTransition(async()=>{await seedVideos();window.location.reload()}); const sync=()=>startTransition(async()=>{await syncArchive();window.location.reload()})
 const submit=(e:React.FormEvent)=>{e.preventDefault();startTransition(async()=>{await addVideo({...form,date:form.date||null,conductor:form.conductor||null,venue:form.venue||null,description:form.description||null,url:form.url||null});window.location.reload()})}
 const filtered=useMemo(()=>videos.filter(v=>{const q=query.toLowerCase();const hay=[v.title,v.conductor,v.venue,v.description].filter(Boolean).join(" ").toLowerCase();const year=filter==="all"||v.date?.startsWith(filter);return year&&hay.includes(q)}),[videos,query,filter])
 const years=Array.from(new Set(videos.map(v=>v.date?.slice(0,4)).filter(Boolean))).sort().reverse()
 return <div className="space-y-5 pb-3">
  <header><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#8a93a6]">Slovenská filharmónia</p><h1 className="font-serif text-[30px] font-semibold tracking-tight">Koncertný archív</h1><p className="mt-1 text-xs text-muted-foreground">Koncerty, interpreti, dirigenti a programy na jednom mieste.</p></div><LibraryBig className="h-7 w-7 text-[#17233d]"/></div></header>
  <div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Hľadať koncert, skladateľa, interpreta…" className="h-11 rounded-xl pl-9"/></div>
  <div className="flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setFilter("all")} className={`rounded-full px-4 py-2 text-xs font-medium ${filter==="all"?"bg-[#17233d] text-white":"bg-[#f0f4fa]"}`}>Všetko</button>{years.map(y=><button key={y} onClick={()=>setFilter(y!)} className={`rounded-full px-4 py-2 text-xs font-medium ${filter===y?"bg-[#eaf1ff] text-blue-700":"bg-[#f0f4fa]"}`}>{y}</button>)}</div>
  <Card className="rounded-2xl border-0 bg-[#17233d] p-5 text-white shadow-none"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-white/55">Archív Slovenskej filharmónie</p><div className="mt-2 flex items-end justify-between gap-4"><div><p className="font-serif text-3xl font-semibold">839</p><p className="text-xs text-white/65">záznamov v pôvodnom archíve</p></div><Button asChild className="rounded-xl bg-white text-[#17233d] hover:bg-white/90"><a href="https://stream.filharmonia.art/concerts" target="_blank" rel="noreferrer">Celý archív <ExternalLink className="ml-2 h-3.5 w-3.5"/></a></Button></div></Card>
  <div className="flex gap-2"><Button onClick={sync} disabled={pending} className="rounded-xl bg-[#17233d]">{pending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<LibraryBig className="mr-2 h-4 w-4"/>}Importovať najnovší výber</Button><Button variant="outline" className="rounded-xl" onClick={()=>setOpen(x=>!x)}><Plus className="mr-2 h-4 w-4"/>Pridať</Button></div>
  {open&&<Card className="rounded-2xl p-4 shadow-none"><form onSubmit={submit} className="grid gap-4"><div><Label>{t.activity}</Label><Input className="mt-1.5" required value={form.title} onChange={e=>set("title",e.target.value)}/></div><div className="grid grid-cols-2 gap-3"><div><Label>{t.date}</Label><Input className="mt-1.5" type="date" value={form.date} onChange={e=>set("date",e.target.value)}/></div><div><Label>{t.position}</Label><Input className="mt-1.5" value={form.conductor} onChange={e=>set("conductor",e.target.value)}/></div></div><div><Label>{t.notes}</Label><Textarea className="mt-1.5" value={form.description} onChange={e=>set("description",e.target.value)}/></div><div><Label>URL</Label><Input className="mt-1.5" type="url" value={form.url} onChange={e=>set("url",e.target.value)}/></div><Button type="submit" disabled={pending}>{t.save}</Button></form></Card>}
  {filtered.length===0?<Card className="p-10 text-center text-sm text-muted-foreground">{videos.length?"Nič sa nenašlo.":t.noVideos}<div className="mt-3"><Button variant="outline" size="sm" onClick={seed} disabled={pending}>Načítať demo archív</Button></div></Card>:<div className="grid gap-5">{filtered.map((v,i)=><Card key={v.id} className="group overflow-hidden rounded-2xl border-0 shadow-sm"><a href={v.url||"https://stream.filharmonia.art/concerts"} target="_blank" rel="noreferrer" className="block"><div className="relative aspect-[16/9] overflow-hidden bg-[#dfe5ef]">{v.thumbnailUrl?<img src={v.thumbnailUrl} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]"/>:<div className="flex h-full items-end bg-gradient-to-br from-[#17233d] via-[#465673] to-[#d9e1ed] p-5"><p className="max-w-[80%] font-serif text-xl font-semibold text-white">{v.title}</p></div>}<div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent"/><div className="absolute bottom-3 left-3 right-3 flex items-end justify-between text-white"><div><p className="text-[10px] font-medium uppercase tracking-[0.16em] text-white/75">{v.date?new Date(v.date+"T00:00:00").toLocaleDateString("sk-SK",{day:"numeric",month:"long",year:"numeric"}):"Koncertný archív"}</p><h2 className="mt-0.5 font-serif text-xl font-semibold leading-tight">{v.title}</h2></div><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-white/95 text-[#17233d] shadow-lg"><Play className="ml-0.5 h-4 w-4 fill-current"/></span></div></div></a><div className="p-4"><p className="text-xs font-medium text-[#17233d]">{v.ensemble||v.venue}</p><p className="mt-1 text-[11px] leading-relaxed text-muted-foreground">{v.program||v.description}</p>{v.conductor&&<p className="mt-2 text-[11px] text-muted-foreground">Dirigent / umelecké vedenie: <span className="font-medium text-foreground">{v.conductor}</span></p>}<Button asChild variant="link" className="mt-2 h-auto p-0 text-xs"><a href={v.url||"https://stream.filharmonia.art/concerts"} target="_blank" rel="noreferrer">Otvoriť záznam <ExternalLink className="ml-1 h-3 w-3"/></a></Button></div></Card>)}</div>}
 </div>
}
