// Source: Slovak Philharmonic work plan, updated 29 July 2026.
// Period: 24 Aug 2026 – 3 Jan 2027.
// This file mirrors the published work-plan schedule; it is not a mock calendar.

export type SeasonActivity = {
  date: string
  type: "rehearsal" | "concert" | "recording" | "dress" | "off" | "ip" | "other"
  startTime: string | null
  endTime: string | null
  title: string
  conductor: string | null
  venue: string | null
  program: string | null
  notes?: string | null
}

export const seasonData: SeasonActivity[] = [
  { date:"2026-08-24", type:"ip", startTime:null, endTime:null, title:"IP", conductor:null, venue:"Slovenská filharmónia", program:null, notes:"Deratizácia – zákaz vstupu do budovy SF." },
  { date:"2026-08-25", type:"ip", startTime:null, endTime:null, title:"IP", conductor:null, venue:"Slovenská filharmónia", program:null },
  { date:"2026-08-26", type:"concert", startTime:null, endTime:null, title:"Koncert v Prezidentskej záhrade", conductor:"Rastislav Štúr", venue:"Prezidentská záhrada, Bratislava", program:"Štátna hymna SR; J. L. Bella: Koncertná predohra Es dur; P. Mascagni: Regina coeli laetare; J. N. Hummel: Koncert pre trúbku a orchester Es dur – 2. Andante, 3. Rondo; A. Dvořák: Měsíčku na nebi hlubokém; Ľ. Rajter: Finále zo Suity z baletu Prešporský majáles; G. Verdi: Gloria all’Egitto; Z. Liška: Valčík z filmu Obchod na korze; G. Verdi: Vedi! le fosche; J. Williams: Hlavná téma zo Schindlerovho zoznamu; J. Williams: The Flight to Neverland; P. Hapka/Ľ. Čekovská: Perinbaba; S. Stračina: Pacho; E. Morricone: Vtedy na Západe; J. Williams: Raiders March; Vangelis: Hudba z filmu 1492." },
  { date:"2026-08-27", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Rastislav Štúr", venue:"Prezidentská záhrada", program:"Program koncertu v Prezidentskej záhrade" },
  { date:"2026-08-27", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúšky / zvuková a kamerová skúška", conductor:"Rastislav Štúr", venue:"Prezidentská záhrada", program:"Dodatočne zvukové a kamerové skúšky; čaká sa na potvrdenie televízie." },
  { date:"2026-08-27", type:"concert", startTime:"20:00", endTime:null, title:"Open air koncert", conductor:"Rastislav Štúr", venue:"Prezidentská záhrada, Bratislava", program:"Koncert bude ozvučený a natáčaný televíziou. Hrá sa vo frakoch." },
  { date:"2026-08-28", type:"concert", startTime:null, endTime:null, title:"Koncert pri fontáne", conductor:"Peter Valentovič", venue:"Bratislava – fontána", program:"Dvořák: Slovanský tanec č. 1 Furiant; Čajkovskij: Labutie jazero; Rimskij-Korsakov: Šeherezáda; Prokofiev: Romeo a Júlia; Korngold: Straussiana; Newman: 20th Century Fox Fanfare; Bernstein: Sedem statočných; Mancini: Ružový panter; J. Williams: Jurský park; J. Williams: Harry Potter; Silvestri: Forrest Gump; Schifrin: Mission Impossible; Badelt: Piráti z Karibiku; J. Williams: Hviezdne vojny – Hlavná téma; J. Williams: Pochod impéria." },
  { date:"2026-08-29", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-08-30", type:"rehearsal", startTime:"14:30", endTime:null, title:"Zvuková skúška / generálka", conductor:null, venue:"Námestie Slobody, Bratislava", program:null },
  { date:"2026-08-30", type:"concert", startTime:"17:00", endTime:null, title:"Open Air koncert", conductor:null, venue:"Námestie Slobody, Bratislava", program:"Koncert v spolupráci s BKIS. Obsadenie sláčikov 12,10,8,6,5. Ozvučený koncert; čierne košele." },
  { date:"2026-08-31", type:"ip", startTime:null, endTime:null, title:"IP", conductor:null, venue:null, program:null },
  { date:"2026-09-01", type:"ip", startTime:null, endTime:null, title:"IP", conductor:null, venue:null, program:null },
  { date:"2026-09-02", type:"ip", startTime:null, endTime:null, title:"IP", conductor:null, venue:null, program:null },
  { date:"2026-09-03", type:"concert", startTime:null, endTime:null, title:"Symfónia umenia", conductor:null, venue:null, program:null, notes:"Zrušená" },
  { date:"2026-09-04", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  ,
  { date:"2026-09-05", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  ,
  { date:"2026-09-06", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  ,
  { date:"2026-09-07", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-08", type:"recording", startTime:"09:00", endTime:"12:00", title:"Nahrávanie propagačného CD", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Jozef Kolkovič: Koncert pre violončelo a orchester Operation Songbird; Iris Szeghy: Koncert pre violončelo a orchester; Mirko Krajči: Koncert pre violončelo a orchester č. 2; Ilja Zeljenka: Koncert pre dve violončelá a sláčikový orchester.", notes:"Sólisti: Ján Slávik, Andrej Gál, Eugen Prochác." },
  { date:"2026-09-08", type:"recording", startTime:"13:30", endTime:"16:30", title:"Nahrávanie propagačného CD", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Pokračovanie nahrávania štyroch koncertov pre violončelo." },
  { date:"2026-09-09", type:"recording", startTime:"09:00", endTime:"13:00", title:"Nahrávanie", conductor:null, venue:"Slovenská filharmónia", program:"Pokračovanie nahrávania propagačného CD." },
  { date:"2026-09-09", type:"other", startTime:"14:30", endTime:null, title:"Konkurz na miesto 2. trubkára", conductor:null, venue:"Slovenská filharmónia", program:null, notes:"Účasť konkurznej komisie a príslušnej skupiny je povinná." },
  { date:"2026-09-10", type:"recording", startTime:"09:00", endTime:"13:00", title:"Nahrávanie", conductor:null, venue:"Slovenská filharmónia", program:"Pokračovanie nahrávania propagačného CD." },
  { date:"2026-09-11", type:"recording", startTime:"09:00", endTime:"13:00", title:"Nahrávanie", conductor:null, venue:"Slovenská filharmónia", program:"Pokračovanie nahrávania propagačného CD." },
  { date:"2026-09-12", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-13", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-14", type:"recording", startTime:"09:00", endTime:"13:00", title:"Nahrávanie – pokračovanie", conductor:null, venue:"Slovenská filharmónia", program:"Pokračovanie nahrávania propagačného CD." },
  { date:"2026-09-15", type:"recording", startTime:"09:00", endTime:"12:00", title:"Nahrávanie", conductor:null, venue:"Slovenská filharmónia", program:"Pokračovanie nahrávania propagačného CD." },
  { date:"2026-09-15", type:"recording", startTime:"13:30", endTime:"16:30", title:"Nahrávanie", conductor:null, venue:"Slovenská filharmónia", program:"Pokračovanie nahrávania propagačného CD." },
  { date:"2026-09-16", type:"recording", startTime:"09:00", endTime:"13:00", title:"Nahrávanie", conductor:null, venue:"Slovenská filharmónia", program:"Pokračovanie nahrávania propagačného CD." },
  { date:"2026-09-17", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-18", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-19", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Simone Young", venue:"Slovenská filharmónia", program:"J. L. Bella: Koncertná predohra Es dur; W. A. Mozart: Koncert pre klavír a orchester č. 21 C dur KV 467; Gustav Mahler: Symfónia č. 1 Titan.", notes:"Sólista: Mao Fujita, klavír." },
  { date:"2026-09-20", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Simone Young", venue:"Slovenská filharmónia", program:"Mahler: Symfónia č. 1 Titan; Mozart: Klavírny koncert č. 21." },
  { date:"2026-09-21", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Simone Young", venue:"Slovenská filharmónia", program:"Mahler: Symfónia č. 1 Titan; Mozart: Klavírny koncert č. 21." },
  { date:"2026-09-22", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Simone Young", venue:"Slovenská filharmónia", program:"Mahler: Symfónia č. 1 Titan; Mozart: Klavírny koncert č. 21." },
  { date:"2026-09-23", type:"dress", startTime:"09:30", endTime:"12:30", title:"Generálka", conductor:"Simone Young", venue:"Slovenská filharmónia", program:"Mahler: Symfónia č. 1 Titan; Mozart: Klavírny koncert č. 21." },
  { date:"2026-09-23", type:"concert", startTime:"19:30", endTime:null, title:"Otvárací koncert BHS", conductor:"Simone Young", venue:"Bratislava", program:"J. L. Bella; Mozart: Klavírny koncert č. 21; Mahler: Symfónia č. 1 Titan." },
  { date:"2026-09-24", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-25", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-26", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-27", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-28", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-29", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-09-30", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Gianluca Capuano", venue:"Slovenská filharmónia", program:"Vincenzo Bellini: Kapuletovci a Montekovci, koncertné uvedenie opery (128 min).", notes:"Vokálni sólisti." },
  { date:"2026-10-01", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Gianluca Capuano", venue:"Slovenská filharmónia", program:"Bellini: Kapuletovci a Montekovci." },
  { date:"2026-10-01", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:"Gianluca Capuano", venue:"Slovenská filharmónia", program:"Bellini: Kapuletovci a Montekovci." },
  { date:"2026-10-02", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Gianluca Capuano", venue:"Slovenská filharmónia", program:"Bellini: Kapuletovci a Montekovci." },
  { date:"2026-10-03", type:"dress", startTime:"10:00", endTime:"14:00", title:"Generálka", conductor:"Gianluca Capuano", venue:"Slovenská filharmónia", program:"Bellini: Kapuletovci a Montekovci." },
  { date:"2026-10-04", type:"concert", startTime:"19:30", endTime:null, title:"Koncert", conductor:"Gianluca Capuano", venue:"Bratislava", program:"Bellini: Kapuletovci a Montekovci, koncertné uvedenie opery." },
  { date:"2026-10-05", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-06", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Yutaka Sado", venue:"Slovenská filharmónia", program:"Gustav Mahler: Symfónia č. 2 Vzkriesenie / Auferstehung (90 min).", notes:"Sólistky: Christina Landshamer, Anna Werle." },
  { date:"2026-10-07", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Yutaka Sado", venue:"Slovenská filharmónia", program:"Mahler: Symfónia č. 2 Vzkriesenie." },
  { date:"2026-10-08", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Yutaka Sado", venue:"Slovenská filharmónia", program:"Mahler: Symfónia č. 2 Vzkriesenie." },
  { date:"2026-10-09", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Yutaka Sado", venue:"Slovenská filharmónia", program:"Mahler: Symfónia č. 2 Vzkriesenie." },
  { date:"2026-10-10", type:"dress", startTime:"10:00", endTime:"13:00", title:"Generálka", conductor:"Yutaka Sado", venue:"Slovenská filharmónia", program:"Mahler: Symfónia č. 2 Vzkriesenie." },
  { date:"2026-10-11", type:"concert", startTime:"19:30", endTime:null, title:"Koncert", conductor:"Yutaka Sado", venue:"Bratislava", program:"Mahler: Symfónia č. 2 Vzkriesenie." },
  { date:"2026-10-12", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-13", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-14", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-15", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-16", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-17", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-18", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-19", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Ondrej Olos", venue:"Stĺpová sieň", program:"Otváracie koncerty 78. koncertnej sezóny: Kilar Orawa; Godár Meditácia; Janáček Putování dušičky; Liszt Danteho symfónia.", notes:"Z dôvodu prenájmovej akcie presunutá do Stĺpovej siene." },
  { date:"2026-10-20", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Otváracie koncerty 78. koncertnej sezóny." },
  { date:"2026-10-20", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Otváracie koncerty 78. koncertnej sezóny." },
  { date:"2026-10-21", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Otváracie koncerty 78. koncertnej sezóny." },
  { date:"2026-10-22", type:"dress", startTime:"09:30", endTime:"12:30", title:"Generálka", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Otváracie koncerty 78. koncertnej sezóny." },
  { date:"2026-10-22", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Ondrej Olos", venue:"Bratislava", program:"Otváracie koncerty 78. koncertnej sezóny." },
  { date:"2026-10-23", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Ondrej Olos", venue:"Bratislava", program:"Otváracie koncerty 78. koncertnej sezóny." },
  { date:"2026-10-24", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-25", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-26", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Rune Bergmann", venue:"Slovenská filharmónia", program:"Rossini: Popoluška; Prokofiev: Klavírny koncert č. 3; Rimskij-Korsakov: Šeherezáda.", notes:"Sólistka: Anastasiia Kliuchereva, klavír. Bábkoherecký súbor Teatro Neline; Martin Vanek, moderátor." },
  { date:"2026-10-26", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:"Rune Bergmann", venue:"Slovenská filharmónia", program:"Rossini: Popoluška; Prokofiev: Klavírny koncert č. 3; Rimskij-Korsakov: Šeherezáda." },
  { date:"2026-10-27", type:"other", startTime:"09:00", endTime:"09:30", title:"Zvuková skúška", conductor:"Rune Bergmann", venue:"Piešťany", program:"Šeherezáda." },
  { date:"2026-10-27", type:"concert", startTime:"10:00", endTime:null, title:"Koncerty Hudobná akadémia", conductor:"Rune Bergmann", venue:"Piešťany", program:"Hrá sa len Šeherezáda." },
  { date:"2026-10-27", type:"concert", startTime:"11:30", endTime:null, title:"Koncerty Hudobná akadémia", conductor:"Rune Bergmann", venue:"Piešťany", program:"Hrá sa len Šeherezáda." },
  { date:"2026-10-28", type:"concert", startTime:"09:30", endTime:null, title:"Koncert Hudobná akadémia", conductor:"Rune Bergmann", venue:"Bratislava", program:"Hrá sa len Šeherezáda." },
  { date:"2026-10-28", type:"concert", startTime:"11:30", endTime:null, title:"Koncert Hudobná akadémia", conductor:"Rune Bergmann", venue:"Bratislava", program:"Hrá sa len Šeherezáda." },
  { date:"2026-10-29", type:"dress", startTime:"09:30", endTime:"13:30", title:"Skúška / generálka", conductor:"Rune Bergmann", venue:"Bratislava", program:"Rossini: Popoluška; Prokofiev: Klavírny koncert č. 3." },
  { date:"2026-10-29", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Rune Bergmann", venue:"Bratislava", program:"Celý program: Rossini, Prokofiev, Rimskij-Korsakov." },
  { date:"2026-10-30", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-10-31", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-01", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-02", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:null, venue:"Slovenská filharmónia", program:"Pracovný plán pre koncert v Prahe pri príležitosti Dňa vzniku samostatného Československa. Program dodatočne po potvrdení.", notes:"Koncert v Prahe bol v pláne s podmienkou potvrdenia; ak sa neuskutoční, koncert v Bratislave 7.11." },
  { date:"2026-11-02", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:null, venue:"Slovenská filharmónia", program:"Príprava programu pre Prahu / Bratislavu." },
  { date:"2026-11-03", type:"other", startTime:"09:00", endTime:null, title:"Odjazd do Prahy / zvuková skúška", conductor:null, venue:"Smetanova sieň Obecného domu, Praha", program:null },
  { date:"2026-11-03", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:null, venue:"Smetanova sieň Obecného domu, Praha", program:"Koncert v Prahe pri príležitosti Dňa vzniku samostatného Československa." },
  { date:"2026-11-04", type:"other", startTime:"09:00", endTime:null, title:"Odjazd do Bratislavy", conductor:null, venue:"Praha → Bratislava", program:null },
  { date:"2026-11-05", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Peter Breiner", venue:"Slovenská filharmónia", program:"Godár: Partita; Albrecht: Tri básne z Rilkeho Života Márie; Kardoš: Hrdinská balada; Moyzes: Partita na poctu Majstra Pavla z Levoče.", notes:"Koncert k Roku slovenskej hudby. Sólistka: Mariana Sajko." },
  { date:"2026-11-05", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:"Peter Breiner", venue:"Slovenská filharmónia", program:"Koncert k Roku slovenskej hudby." },
  { date:"2026-11-06", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Peter Breiner", venue:"Slovenská filharmónia", program:"Koncert k Roku slovenskej hudby." },
  { date:"2026-11-07", type:"dress", startTime:"09:30", endTime:"12:30", title:"Generálka", conductor:"Peter Breiner", venue:"Slovenská filharmónia", program:"Koncert k Roku slovenskej hudby." },
  { date:"2026-11-07", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Peter Breiner", venue:"Bratislava", program:"Koncert k Roku slovenskej hudby." },
  { date:"2026-11-08", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-09", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Juraj Valčuha", venue:"Slovenská filharmónia", program:"Respighi: Rímske fontány; Ravel: Šeherezáda; Prokofiev: Symfónia č. 7 cis mol." },
  { date:"2026-11-10", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Juraj Valčuha", venue:"Slovenská filharmónia", program:"Respighi; Ravel; Prokofiev." },
  { date:"2026-11-10", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:"Juraj Valčuha", venue:"Slovenská filharmónia", program:"Respighi; Ravel; Prokofiev." },
  { date:"2026-11-11", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Juraj Valčuha", venue:"Slovenská filharmónia", program:"Respighi; Ravel; Prokofiev." },
  { date:"2026-11-12", type:"dress", startTime:"09:30", endTime:"12:30", title:"Generálka", conductor:"Juraj Valčuha", venue:"Slovenská filharmónia", program:"Respighi; Ravel; Prokofiev." },
  { date:"2026-11-12", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Juraj Valčuha", venue:"Bratislava", program:"Respighi; Ravel; Prokofiev." },
  { date:"2026-11-13", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Juraj Valčuha", venue:"Bratislava", program:"Respighi; Ravel; Prokofiev." },
  { date:"2026-11-14", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-15", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-16", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Wayne Marshall", venue:"Slovenská filharmónia", program:"Poulenc: Koncert g mol pre organ; Holst: Planéty." },
  { date:"2026-11-17", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Wayne Marshall", venue:"Slovenská filharmónia", program:"Poulenc: Organový koncert; Holst: Planéty." },
  { date:"2026-11-17", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:"Wayne Marshall", venue:"Slovenská filharmónia", program:"Poulenc: Organový koncert; Holst: Planéty." },
  { date:"2026-11-18", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Wayne Marshall", venue:"Slovenská filharmónia", program:"Poulenc: Organový koncert; Holst: Planéty." },
  { date:"2026-11-19", type:"dress", startTime:"09:30", endTime:"12:30", title:"Generálka", conductor:"Wayne Marshall", venue:"Slovenská filharmónia", program:"Poulenc: Organový koncert; Holst: Planéty." },
  { date:"2026-11-19", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Wayne Marshall", venue:"Bratislava", program:"Poulenc: Koncert g mol; Holst: Planéty." },
  { date:"2026-11-20", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Wayne Marshall", venue:"Bratislava", program:"Poulenc: Koncert g mol; Holst: Planéty." },
  { date:"2026-11-21", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-22", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-23", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Jan Kučera", venue:"Slovenská filharmónia", program:"Štefan Margita 70: Mozart, Čajkovskij, Verdi, Cilea, Wagner, Bernstein, Gershwin, Dvořák, Smetana, Janáček; prídavky Lehár, Verdi." },
  { date:"2026-11-23", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:"Jan Kučera", venue:"Nahrávacie štúdio -206", program:"Štefan Margita 70." , notes:"Z dôvodu prenájmovej akcie budú skúšky v nahrávacom štúdiu -206."},
  { date:"2026-11-24", type:"other", startTime:"09:00", endTime:null, title:"Konkurz na miesto tutti hráča v skupine viol", conductor:null, venue:"Slovenská filharmónia", program:null, notes:"Konkurz na bicie bol zrušený. Účasť konkurznej komisie a príslušnej skupiny je povinná." },
  { date:"2026-11-24", type:"other", startTime:"14:00", endTime:null, title:"Konkurz na miesto 1. trubkára", conductor:null, venue:"Slovenská filharmónia", program:"Povinnosť hrať na piccolo trúbke.", notes:"Účasť konkurznej komisie a príslušnej skupiny je povinná." },
  { date:"2026-11-25", type:"dress", startTime:"11:00", endTime:"14:00", title:"Generálka", conductor:"Jan Kučera", venue:"Bratislava", program:"Štefan Margita 70." },
  { date:"2026-11-26", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Jan Kučera", venue:"Bratislava", program:"Štefan Margita 70." },
  { date:"2026-11-27", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-28", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-29", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-11-30", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Dohnányi: Symfonické minúty; Németh-Šamorínsky: Koncert pre organ; Čajkovskij: Spiaca krásavica." , notes:"Sólista: Marek Vrábel, organ."},
  { date:"2026-12-01", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Dohnányi; Németh-Šamorínsky; Čajkovskij." },
  { date:"2026-12-01", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Dohnányi; Németh-Šamorínsky; Čajkovskij." },
  { date:"2026-12-02", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Dohnányi; Németh-Šamorínsky; Čajkovskij." },
  { date:"2026-12-03", type:"dress", startTime:"09:30", endTime:"12:30", title:"Generálka", conductor:"Ondrej Olos", venue:"Slovenská filharmónia", program:"Dohnányi; Németh-Šamorínsky; Čajkovskij." },
  { date:"2026-12-03", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Ondrej Olos", venue:"Bratislava", program:"Dohnányi; Németh-Šamorínsky; Čajkovskij." },
  { date:"2026-12-04", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Ondrej Olos", venue:"Bratislava", program:"Dohnányi; Németh-Šamorínsky; Čajkovskij." },
  { date:"2026-12-05", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-06", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-07", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Kaspar Zehnder", venue:"Slovenská filharmónia", program:"Mel Bonis: Trois femmes de légendes; Poulenc: Koncert pre dva klavíry; Dvořák: Symfónia č. 5 F dur." , notes:"Sólisti: Marián Lapšanský, Matej Arendárik, klavír."},
  { date:"2026-12-08", type:"rehearsal", startTime:"09:00", endTime:"12:00", title:"Skúška", conductor:"Kaspar Zehnder", venue:"Slovenská filharmónia", program:"Mel Bonis; Poulenc; Dvořák." },
  { date:"2026-12-08", type:"rehearsal", startTime:"13:30", endTime:"16:30", title:"Skúška", conductor:"Kaspar Zehnder", venue:"Slovenská filharmónia", program:"Mel Bonis; Poulenc; Dvořák." },
  { date:"2026-12-09", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška", conductor:"Kaspar Zehnder", venue:"Slovenská filharmónia", program:"Mel Bonis; Poulenc; Dvořák." },
  { date:"2026-12-09", type:"other", startTime:"14:00", endTime:null, title:"Konkurz na miesto prvého hráča v skupine viol", conductor:null, venue:"Slovenská filharmónia", program:null, notes:"Účasť konkurznej komisie a príslušnej skupiny je povinná." },
  { date:"2026-12-10", type:"dress", startTime:"09:30", endTime:"12:30", title:"Generálka", conductor:"Kaspar Zehnder", venue:"Slovenská filharmónia", program:"Mel Bonis; Poulenc; Dvořák." },
  { date:"2026-12-10", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Kaspar Zehnder", venue:"Bratislava", program:"Mel Bonis; Poulenc; Dvořák." },
  { date:"2026-12-11", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Kaspar Zehnder", venue:"Bratislava", program:"Mel Bonis; Poulenc; Dvořák." },
  { date:"2026-12-12", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-13", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-14", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-15", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška – vianočné koncerty", conductor:"Lukáš Vasilek", venue:"Slovenská filharmónia", program:"Jiří Gemrot: Cesta adventem (premiéra); W. A. Mozart: Vesperae solennes de Dominica KV 321." , notes:"Pražský filharmonický sbor; Veronika Rovná, Lucie Hilscherová, Martin Šrejma, Jiří Brückler, Pavel Švingr."},
  { date:"2026-12-16", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška – vianočné koncerty", conductor:"Lukáš Vasilek", venue:"Slovenská filharmónia", program:"Cesta adventem; Mozart: Vesperae solennes de Dominica." },
  { date:"2026-12-17", type:"other", startTime:"07:58", endTime:"12:30", title:"Cesta vlakom Bratislava – Praha", conductor:null, venue:"Bratislava → Praha", program:null },
  { date:"2026-12-17", type:"rehearsal", startTime:"14:00", endTime:"18:00", title:"Skúška", conductor:"Lukáš Vasilek", venue:"Skúšobňa Hostivař, Praha", program:"Vianočné koncerty." },
  { date:"2026-12-18", type:"dress", startTime:null, endTime:null, title:"Generálka", conductor:"Lukáš Vasilek", venue:"Žofín, Praha", program:"Dodatočne generálka na Žofíne." },
  { date:"2026-12-18", type:"concert", startTime:"19:30", endTime:null, title:"1. koncert", conductor:"Lukáš Vasilek", venue:"Žofín, Praha", program:"Vianočné koncerty." },
  { date:"2026-12-19", type:"concert", startTime:"14:30", endTime:null, title:"2. koncert", conductor:"Lukáš Vasilek", venue:"Žofín, Praha", program:"Vianočné koncerty." , notes:"Po koncerte cesta z Prahy do Bratislavy."},
  { date:"2026-12-20", type:"rehearsal", startTime:"16:00", endTime:"17:00", title:"Zvuková skúška", conductor:"Lukáš Vasilek", venue:"Slovenská filharmónia", program:"Vianočné koncerty." },
  { date:"2026-12-20", type:"concert", startTime:"19:00", endTime:null, title:"Koncert", conductor:"Lukáš Vasilek", venue:"Slovenská filharmónia", program:"Vianočné koncerty." },
  { date:"2026-12-21", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-22", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-23", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-24", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-25", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-26", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-27", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
  { date:"2026-12-28", type:"rehearsal", startTime:"09:00", endTime:"13:00", title:"Skúška – Silvestrovský / Novoročný koncert", conductor:"Erik Nielsen", venue:"Slovenská filharmónia", program:"Árie a zbory z opier W. A. Mozarta, G. Rossiniho, P. I. Čajkovského, G. Verdiho a R. Wagnera.", notes:"Sólista: Dalibor Jenis, barytón." },
  { date:"2026-12-29", type:"rehearsal", startTime:"10:00", endTime:"14:00", title:"Skúška", conductor:"Erik Nielsen", venue:"Slovenská filharmónia", program:"Silvestrovský / Novoročný koncert." },
  { date:"2026-12-30", type:"rehearsal", startTime:"10:00", endTime:"14:00", title:"Skúška", conductor:"Erik Nielsen", venue:"Slovenská filharmónia", program:"Silvestrovský / Novoročný koncert." },
  { date:"2026-12-31", type:"dress", startTime:"10:00", endTime:"13:00", title:"Generálka", conductor:"Erik Nielsen", venue:"Slovenská filharmónia", program:"Silvestrovský / Novoročný koncert." },
  { date:"2026-12-31", type:"concert", startTime:"16:00", endTime:null, title:"Silvestrovský koncert", conductor:"Erik Nielsen", venue:"Slovenská filharmónia", program:"Árie a zbory z opier Mozarta, Rossiniho, Čajkovského, Verdiho a Wagnera." },
  { date:"2027-01-01", type:"concert", startTime:"19:00", endTime:null, title:"Novoročný koncert", conductor:"Erik Nielsen", venue:"Slovenská filharmónia", program:"Árie a zbory z opier Mozarta, Rossiniho, Čajkovského, Verdiho a Wagnera." },
  { date:"2027-01-02", type:"concert", startTime:"19:00", endTime:null, title:"Novoročný koncert", conductor:"Erik Nielsen", venue:"Slovenská filharmónia", program:"Árie a zbory z opier Mozarta, Rossiniho, Čajkovského, Verdiho a Wagnera." },
  { date:"2027-01-03", type:"off", startTime:null, endTime:null, title:"Voľno", conductor:null, venue:null, program:null },
]
